version: '3'
services: 
  enodeb:
    image: oaisoftwarealliance/oai-enb:2024.w29
    privileged: true
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    env_file:
    - config/enb/enb.env
    cap_add:
      - all
